// 语言资源文件
const translations = {
  'zh-CN': {
    title: '高考大捷 - 为梦想而战',
    navNews: 'News',
    navArchive: '往期内容',
    navAbout: '关于我们',
    footer: '萌ICP备20250941号',
    homeTitle: '高考大捷',
    homeSubtitle: '',
    countdownLabel: '距离高考还有',
    motivationalText: '十年寒窗苦读，一朝金榜题名',
    blessingText: '愿所有考生都能发挥出最好的水平，收获理想的成绩！',
    ctaText: '查看备考资料',
    examDate: '2025年6月7日 上午8:00',
    days: '天',
    hours: '小时',
    minutes: '分钟',
    seconds: '秒'
  },
  'zh-TW': {
    title: '高考大捷 - 為夢想而戰',
    navNews: '新聞',
    navArchive: '往期內容',
    navAbout: '關於我們',
    footer: '萌ICP備20250941號',
    homeTitle: '高考大捷',
    homeSubtitle: '',
    countdownLabel: '距離高考還有',
    motivationalText: '十年寒窗苦讀，一朝金榜題名',
    blessingText: '願所有考生都能發揮出最好的水平，收穫理想的成績！',
    ctaText: '查看備考資料',
    examDate: '2025年6月7日 上午8:00',
    days: '天',
    hours: '小時',
    minutes: '分鐘',
    seconds: '秒'
  },
  'en': {
    title: 'Gaokao Success - Fight for Your Dreams',
    navNews: 'News',
    navArchive: 'Archive',
    navAbout: 'About Us',
    footer: 'MoeICP No.20250941',
    homeTitle: 'Gaokao Success',
    homeSubtitle: '',
    countdownLabel: 'Time until Gaokao',
    motivationalText: 'Years of hard work, moment of triumph',
    blessingText: 'May all students perform their best and achieve their dreams!',
    ctaText: 'View Study Materials',
    examDate: 'June 7, 2025 8:00 AM',
    days: 'Days',
    hours: 'Hours',
    minutes: 'Minutes',
    seconds: 'Seconds'
  },
  'ja': {
    title: '高考成功 - 夢のために戦え',
    navNews: 'ニュース',
    navArchive: 'アーカイブ',
    navAbout: '私たちについて',
    footer: 'MoeICP No.20250941',
    homeTitle: '高考大捷',
    homeSubtitle: '',
    countdownLabel: '高考まであと',
    motivationalText: '十年の努力が実を結ぶ瞬間',
    blessingText: 'すべての受験生が最高の結果を出せますように！',
    ctaText: '学習資料を見る',
    examDate: '2025年6月7日 午前8:00',
    days: '日',
    hours: '時間',
    minutes: '分',
    seconds: '秒'
  },
  'ru': {
    title: 'Успех на Гаокао - Борись за мечту',
    navNews: 'Новости',
    navArchive: 'Архив',
    navAbout: 'О нас',
    footer: 'MoeICP №20250941',
    homeTitle: 'Успех на Гаокао',
    homeSubtitle: '',
    countdownLabel: 'До экзамена Гаокао осталось',
    motivationalText: 'Годы упорного труда ради одного триумфа',
    blessingText: 'Пусть все студенты покажут лучшие результаты и достигнут мечты!',
    ctaText: 'Посмотреть материалы',
    examDate: '7 июня 2025 8:00',
    days: 'дн.',
    hours: 'ч.',
    minutes: 'мин.',
    seconds: 'сек.'
  },
  'th': {
    title: 'ประสบความสำเร็จในการสอบเข้ามหาวิทยาลัย - สู้เพื่อความฝัน',
    navNews: 'ข่าว',
    navArchive: 'คลังข่าว',
    navAbout: 'เกี่ยวกับเรา',
    footer: 'MoeICP No.20250941',
    homeTitle: 'Gaokao Success',
    homeSubtitle: '',
    countdownLabel: 'เหลือเวลาอีกก่อนสอบ Gaokao',
    motivationalText: 'ทุ่มเทมาเป็นเวลานาน สู่ชัยชนะเพียงข้ามคืน',
    blessingText: 'ขอให้ทุกคนทำได้ดีที่สุดและสมหวัง!',
    ctaText: 'ดูเอกสารเตรียมสอบ',
    examDate: '7 มิถุนายน 2025 08:00 น.',
    days: 'วัน',
    hours: 'ชั่วโมง',
    minutes: 'นาที',
    seconds: 'วินาที'
  },
  'de': {
    title: 'Gaokao-Erfolg - Kämpfe für deine Träume',
    navNews: 'Nachrichten',
    navArchive: 'Archiv',
    navAbout: 'Über uns',
    footer: 'MoeICP Nr.20250941',
    homeTitle: 'Gaokao-Erfolg',
    homeSubtitle: '',
    countdownLabel: 'Zeit bis zum Gaokao',
    motivationalText: 'Jahre harter Arbeit für den Moment des Erfolgs',
    blessingText: 'Möge jeder Schüler sein Bestes geben und seine Träume erreichen!',
    ctaText: 'Lernmaterial ansehen',
    examDate: '7. Juni 2025 8:00',
    days: 'Tage',
    hours: 'Stunden',
    minutes: 'Minuten',
    seconds: 'Sekunden'
  },
  'fr': {
    title: 'Réussite au Gaokao - Lutte pour tes rêves',
    navNews: 'Actualités',
    navArchive: 'Archives',
    navAbout: 'À propos',
    footer: 'MoeICP n°20250941',
    homeTitle: 'Réussite au Gaokao',
    homeSubtitle: '',
    countdownLabel: 'Temps avant le Gaokao',
    motivationalText: 'Des années d\'efforts pour un moment de gloire',
    blessingText: 'Que tous les étudiants donnent le meilleur d\'eux-mêmes et réalisent leurs rêves !',
    ctaText: 'Voir les documents',
    examDate: '7 juin 2025 8:00',
    days: 'Jours',
    hours: 'Heures',
    minutes: 'Minutes',
    seconds: 'Secondes'
  },
  'es': {
    title: 'Éxito en el Gaokao - Lucha por tus sueños',
    navNews: 'Noticias',
    navArchive: 'Archivo',
    navAbout: 'Sobre nosotros',
    footer: 'MoeICP Nº20250941',
    homeTitle: 'Éxito en el Gaokao',
    homeSubtitle: '',
    countdownLabel: 'Tiempo hasta el Gaokao',
    motivationalText: 'Años de esfuerzo para un momento de triunfo',
    blessingText: '¡Que todos los estudiantes den lo mejor y alcancen sus sueños!',
    ctaText: 'Ver materiales de estudio',
    examDate: '7 de junio de 2025 8:00',
    days: 'Días',
    hours: 'Horas',
    minutes: 'Minutos',
    seconds: 'Segundos'
  }
};
