// 语言资源文件
const translations = {
  'zh-CN': {
    title: '高考大捷 - 为梦想而战',
    navNews: 'News',
    navArchive: '往期内容',
    navAbout: '关于我们',
    footer: '萌ICP备20250941号',
    homeTitle: '高考大捷',
    homeSubtitle: '',
    countdownLabel: '距离高考还有',
    motivationalText: '十年寒窗苦读，一朝金榜题名',
    blessingText: '愿所有考生都能发挥出最好的水平，收获理想的成绩！',
    ctaText: '查看备考资料',
    examDate: '2025年6月7日 上午8:00',
    days: '天',
    hours: '小时', 
    minutes: '分钟',
    seconds: '秒',
    publishDate: '发布时间：2024年8月21日',
    announcement: '我们很高兴地宣布，SBS最新作品「水语」已经正式发表。欢迎大家查看和下载。',
    downloadButton: '点击下载PDF'
  },
  'en': {
    title: 'Gaokao Success - Fight for Your Dreams',
    navNews: 'News',
    navArchive: 'Archive', 
    navAbout: 'About Us',
    footer: 'MoeICP No.20250941',
    homeTitle: 'Gaokao Success',
    homeSubtitle: '',
    countdownLabel: 'Time until Gaokao',
    motivationalText: 'Years of hard work, moment of triumph',
    blessingText: 'May all students perform their best and achieve their dreams!',
    ctaText: 'View Study Materials',
    examDate: 'June 7, 2025 8:00 AM',
    days: 'Days',
    hours: 'Hours',
    minutes: 'Minutes',
    seconds: 'Seconds',
    publishDate: 'Published on August 21, 2024',
    announcement: 'We are excited to announce that SBS\'s latest work, "Water Language", has officially been released. Feel free to check it out and download.',
    downloadButton: 'Download PDF'
  }
};
